document.write(" <h1> Rules for naming JS variables </h1>")
document.write("Variable names can only contain <b>number</b>, <b>$</b>, and <b>_</b> . For example $my_1stVariable.   <br>")
document.write("Variables must begin with a <b>letter</b>, <b>$</b>, or <b>_</b>. For example $name, _name or name.   <br>")
document.write("Variable names are case <b>sensitive</b>.  <br>")
document.write("Variable names should not be JS  <b>keywords</b>.  <br>")